version: '3.9'
services:
  users_backend:
    container_name: users_micro_service
    build: .
    ports:
      - 8001:8000
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - users
  users_db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: users
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    volumes:
      - ./storage/dbdata:/var/lib/mysql
    networks:
      - users
networks:
 users:
  name: users

